services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=${{ secrets.DB_USER }}
      - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${{ secrets.DB_SOURCE }}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true