name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create app.env file
        run: |
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> app.env
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
          echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> app.env
          echo "ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }}" >> app.env
      
      - name: Set up SSH (read-write permission) and add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem 
          ssh-keyscan arva888.xyz >> ~/.ssh/known_hosts
  
      - name: Transfer app.env to VPS
        uses: appleboy/scp-action@master
        with:
          host: arva888.xyz
          username: arvalinno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.env"
          target: "/home/arvalinno/app/"

      - name: Update code on VPS (git pull)
        uses: appleboy/ssh-action@master
        with:
          host: arva888.xyz
          username: arvalinno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/arvalinno/app
            git pull origin main

      - name: Build Docker images on VPS
        uses: appleboy/ssh-action@master
        with:
          host: arva888.xyz
          username: arvalinno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/arvalinno/app
            docker compose build --no-cache

      - name: Deploy application using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: arva888.xyz
          username: arvalinno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/arvalinno/app
            docker compose down && docker compose up -d