name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create app.env file
        run: |
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> app.env
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
          echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> app.env
          echo "ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }}" >> app.env
      
      - name: Create .ssh directory and add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan arva888.xyz >> ~/.ssh/known_hosts

      - name: Transfer app.env to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem app.env arvalinno@arva888.xyz:/home/arvalinno/app

      - name: Build Docker images on VPS
        run: |
          ssh -i private_key.pem arvalinno@arva888.xyz "cd /home/arvalinno/app && docker compose build --no-cache"

      - name: Deploy application using Docker Compose
        run: |
          ssh -i private_key.pem arvalinno@arva888.xyz "cd /home/arvalinno/app && docker compose down && docker compose up -d"