name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create app.env file
        run: |
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> app.env
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
          echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> app.env
          echo "ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }}" >> app.env
      
      - name: Set up SSH (read-write permission) and add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY_1}" > private_key.pem
          chmod 600 private_key.pem 
          ssh-keyscan ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts
        
      - name: Update code on VPS (git pull)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
          script: |
            mkdir -p app
            cd /home/${{ secrets.SSH_USERNAME }}/app
            # Check if .git directory exists (indicating it's a Git repo)
            if [ -d ".git" ]; then
              echo "Git repository exists, pulling the latest changes..."
              git pull origin main
            else
              echo "Not a Git repository, cloning repository..."
              git clone https://github.com/arvalinno/simplebank.git .
            fi

      - name: Transfer app.env to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
          source: "app.env"
          target: "/home/${{ secrets.SSH_USERNAME }}/app/"

      - name: Load app.env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/app
            source app.env

      - name: Build Docker images on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/app
            docker compose build --no-cache

      - name: Deploy application using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
          script: |
            # Pass environment variables to Docker Compose
            cd /home/${{ secrets.SSH_USERNAME }}/app
            DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD DB_NAME=$DB_NAME DB_DRIVER=$DB_DRIVER docker compose down && docker compose up -d